# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vxod.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_vxod(object):
    def setupUi(self, vxod):
        vxod.setObjectName("vxod")
        vxod.resize(421, 349)
        self.pushButton = QtWidgets.QPushButton(vxod)
        self.pushButton.setGeometry(QtCore.QRect(100, 240, 221, 41))
        self.pushButton.setStyleSheet("background-color: rgb(185, 198, 241);\n"
"background-color: rgb(170, 255, 127);\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget = QtWidgets.QWidget(vxod)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 381, 73))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(vxod)
        self.lineEdit.setGeometry(QtCore.QRect(80, 120, 261, 41))
        self.lineEdit.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(vxod)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 180, 261, 41))
        self.lineEdit_2.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(vxod)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 290, 221, 41))
        self.pushButton_2.setStyleSheet("background-color: rgb(182, 196, 238);\n"
"background-color: rgb(170, 255, 127);")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(vxod)
        QtCore.QMetaObject.connectSlotsByName(vxod)

    def retranslateUi(self, vxod):
        _translate = QtCore.QCoreApplication.translate
        vxod.setWindowTitle(_translate("vxod", "Form"))
        self.pushButton.setText(_translate("vxod", "Зарегистрироваться"))
        self.label.setText(_translate("vxod", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">Вход</span></p></body></html>"))
        self.label_2.setText(_translate("vxod", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.pushButton_2.setText(_translate("vxod", "Войти"))
